import strings from "../locales/localization";

const category = strings.const.categoryForSearch

export const categoryForSearchRu = [
    'отдых',
    'релаксация',
    'мотивационным',
    'вакцина',
    'думать',
    'энергия',
    'солнечный свет',
    'корабль',
    'самолет',
    'робот',
    'прут',
    'зеркало',
    'природа',
    'оружие',
    'автомобили',
    'уход за кожей',
    'досуг',
    'размытый',
    'мирный',
    'массаж',
    'женщина',
    'спа',
    'цветы',
    'обои',
    'деньги',
    'собака',
    'кот',
    'небо',
    'любовь',
    'короновирус',
    'бизнес',
    'еда',
    'животные',
    'ящерица',
    'лето',
    'дорога',
    'лес',
    'зима',
    'осень',
    'весна',
]

export const categoryForSearchEn = [
    'rest',
    'relaxation',
    'motivational',
    'vaccine',
    'think',
    'energy',
    'sunshine',
    'ship',
    'plane',
    'robot',
    'rod',
    'mirror',
    'nature',
    'weapon',
    'cars',
    'skin care',
    'leisure',
    'blurry',
    'peaceful',
    'massage',
    'woman',
    'spa',
    'flowers',
    'wallpaper',
    'money',
    'dog',
    'cat',
    'sky',
    'love',
    'coronavirus',
    'business',
    'food',
    'animals',
    'lizard',
    'summer',
    'road',
    'forest',
    'winter',
    'autumn',
    'spring',
]