import strings from "../locales/localization";

const category = strings.const.categoryForSearch

export const categoryForSearch = [
    category.rest,
    category.relaxation,
    category.motivational,
    category.vaccine,
    category.think,
    category.energy,
    category.sunshine,
    category.ship,
    category.plane,
    category.robot,
    category.rod,
    category.mirror,
    category.nature,
    category.weapon,
    category.cars,
    category.skinCare,
    category.leisure,
    category.blurry,
    category.peaceful,
    category.massage,
    category.woman,
    category.spa,
    category.flowers,
    category.wallpaper,
    category.money,
    category.dog,
    category.cat,
    category.sky,
    category.love,
    category.coronavirus,
    category.business,
    category.food,
    category.animals,
    category.lizard,
    category.summer,
    category.road,
    category.forest,
    category.winter,
    category.autumn,
    category.spring,
]